[package]
name = "database_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
postgres = "0.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio-postgres = "0.7.13"
chrono = "0.4.39"
regex = "1.11.1"
strsim = "0.11.1"
